terraform { required_version = ">= 1.6.0" required_providers { aws = { source = "hashicorp/aws" version = "~> 5.0" } } }
locals { name = "taskmind-${var.environment}" tags = merge(var.tags, { Project = "taskmind", Environment = var.environment, ManagedBy = "opentofu" }) }
resource "aws_security_group" "alb" { name = "${local.name}-alb" vpc_id = var.vpc_id ingress { from_port = 80 to_port = 80 protocol = "tcp" cidr_blocks = ["0.0.0.0/0"] } ingress { from_port = 443 to_port = 443 protocol = "tcp" cidr_blocks = ["0.0.0.0/0"] } egress { from_port = 0 to_port = 0 protocol = "-1" cidr_blocks = ["0.0.0.0/0"] } tags = local.tags }
resource "aws_lb" "core" { name = "${local.name}-core" load_balancer_type = "application" internal = false security_groups = [aws_security_group.alb.id] subnets = var.public_subnet_ids idle_timeout = 3600 tags = local.tags }
resource "aws_lb_target_group" "core" { name = "${local.name}-core" port = 8080 protocol = "HTTP" target_type = "ip" vpc_id = var.vpc_id health_check { path = "/actuator/health" matcher = "200-399" } tags = local.tags }
resource "aws_lb_listener" "http" { load_balancer_arn = aws_lb.core.arn port = 80 protocol = "HTTP" default_action { type = var.alb_certificate_arn == null ? "forward" : "redirect" target_group_arn = var.alb_certificate_arn == null ? aws_lb_target_group.core.arn : null dynamic "redirect" { for_each = var.alb_certificate_arn == null ? [] : [1] content { port = "443" protocol = "HTTPS" status_code = "HTTP_301" } } } }
resource "aws_lb_listener" "https" { count = var.alb_certificate_arn == null ? 0 : 1 load_balancer_arn = aws_lb.core.arn port = 443 protocol = "HTTPS" certificate_arn = var.alb_certificate_arn default_action { type = "forward" target_group_arn = aws_lb_target_group.core.arn } }
resource "aws_wafv2_web_acl" "core" { name = "${local.name}-core" scope = "REGIONAL" default_action { allow {} } rule { name = "aws-common" priority = 1 override_action { none {} } statement { managed_rule_group_statement { name = "AWSManagedRulesCommonRuleSet" vendor_name = "AWS" } } visibility_config { cloudwatch_metrics_enabled = true metric_name = "common" sampled_requests_enabled = true } } rule { name = "rate-limit" priority = 2 action { block {} } statement { rate_based_statement { limit = var.waf_rate_limit aggregate_key_type = "IP" } } visibility_config { cloudwatch_metrics_enabled = true metric_name = "rateLimit" sampled_requests_enabled = true } } visibility_config { cloudwatch_metrics_enabled = true metric_name = "${local.name}-core" sampled_requests_enabled = true } tags = local.tags }
resource "aws_wafv2_web_acl_association" "core" { resource_arn = aws_lb.core.arn web_acl_arn = aws_wafv2_web_acl.core.arn }
resource "aws_cloudfront_origin_access_control" "spa" { name = "${local.name}-spa" description = "OAC for TaskMind SPA artifacts" origin_access_control_origin_type = "s3" signing_behavior = "always" signing_protocol = "sigv4" }
resource "aws_cloudfront_distribution" "spa" { enabled = true aliases = var.frontend_aliases default_root_object = "index.html" origin { domain_name = var.frontend_bucket_regional_domain_name origin_id = "frontend-s3" origin_access_control_id = aws_cloudfront_origin_access_control.spa.id } default_cache_behavior { target_origin_id = "frontend-s3" viewer_protocol_policy = "redirect-to-https" allowed_methods = ["GET", "HEAD", "OPTIONS"] cached_methods = ["GET", "HEAD"] compress = true forwarded_values { query_string = false cookies { forward = "none" } } } custom_error_response { error_code = 403 response_code = 200 response_page_path = "/index.html" } custom_error_response { error_code = 404 response_code = 200 response_page_path = "/index.html" } restrictions { geo_restriction { restriction_type = "none" } } viewer_certificate { acm_certificate_arn = var.cloudfront_certificate_arn ssl_support_method = var.cloudfront_certificate_arn == null ? null : "sni-only" cloudfront_default_certificate = var.cloudfront_certificate_arn == null } tags = local.tags }
