server:
  port: 8082

spring:
  application:
    name: taskmind-ai
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: ai
    default-schema: ai
    locations: classpath:db/migration
