package com.taskmind.backend.specbreakdown.interfaces.rest;
import com.taskmind.backend.auth.AuthenticatedUser; import com.taskmind.backend.specbreakdown.application.*; import com.taskmind.backend.specbreakdown.domain.model.*; import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import jakarta.validation.constraints.NotNull; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/v1/spec-breakdown")
public class SpecBreakdownController { private final SpecBreakdownApplicationService service; public SpecBreakdownController(SpecBreakdownApplicationService service){this.service=service;}
 @PostMapping("/drafts") public ResponseEntity<?> create(AuthenticatedUser u,@Valid @RequestBody CreateDraftRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(service.createDraft(u,new SpecBreakdownApplicationService.CreateDraftCommand(r.projectId(),r.templateId(),r.title(),r.rawSpec(),r.richContent(),r.candidateTree(),r.fixVersion(),r.affectedVersion(),r.sprint(),r.issueType(),r.publishKey())));}
 @GetMapping("/drafts/{id}") public Object get(AuthenticatedUser u,@PathVariable UUID id){return service.getDraft(u,id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 @PostMapping("/drafts/{id}/jobs") public ResponseEntity<?> start(AuthenticatedUser u,@PathVariable UUID id,@Valid @RequestBody StartJobRequest r){try{return ResponseEntity.status(HttpStatus.ACCEPTED).body(service.startJob(u,id,r.aiJobType()));}catch(IllegalArgumentException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,e.getMessage(),e);}}
 @GetMapping("/jobs/{id}") public Object job(AuthenticatedUser u,@PathVariable UUID id){return service.getJob(u,id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));}
 @PostMapping("/jobs/{id}/{command:pause|resume|cancel}") public Object command(AuthenticatedUser u,@PathVariable UUID id,@PathVariable String command){return service.commandJob(u,id,command);}
 @PostMapping("/drafts/{id}/review") public Object review(AuthenticatedUser u,@PathVariable UUID id,@RequestBody ReviewRequest r){return service.review(u,id,new SpecBreakdownApplicationService.ReviewCommand(r.accepted(),r.candidateTree()));}
 @PostMapping("/drafts/{id}/materialize") public Map<String,Object> materialize(AuthenticatedUser u,@PathVariable UUID id){return Map.of("taskIds",service.materialize(u,id));}
 public record CreateDraftRequest(@NotNull UUID projectId,UUID templateId,@NotBlank String title,@NotBlank String rawSpec,String richContent,String candidateTree,String fixVersion,String affectedVersion,String sprint,String issueType,String publishKey){} public record StartJobRequest(@NotNull SpecBreakdownJobType aiJobType){} public record ReviewRequest(boolean accepted,String candidateTree){}
}
