terraform { required_version = ">= 1.6.0" required_providers { aws = { source = "hashicorp/aws" version = "~> 5.0" } } }
locals { name = "taskmind-${var.environment}" tags = merge(var.tags, { Project = "taskmind", Environment = var.environment, ManagedBy = "opentofu" }) services = { core = { port = 8080, cpu = 1024, memory = 2048, desired = var.core_desired_count, public = true }, relay = { port = 8081, cpu = 512, memory = 1024, desired = var.relay_desired_count, public = false }, nova = { port = 8082, cpu = 1024, memory = 2048, desired = var.nova_desired_count, public = false } } service_secret_arns = { core = var.core_secret_arns, relay = var.relay_secret_arns, nova = var.nova_secret_arns } }
resource "aws_ecs_cluster" "this" { name = local.name setting { name = "containerInsights" value = "enabled" } tags = local.tags }
resource "aws_service_discovery_private_dns_namespace" "this" { name = "taskmind.local" vpc = var.vpc_id tags = local.tags }
resource "aws_security_group" "ecs" { name = "${local.name}-ecs" vpc_id = var.vpc_id ingress { description = "Core from ALB" from_port = 8080 to_port = 8080 protocol = "tcp" security_groups = [var.alb_security_group_id] } ingress { description = "Internal service calls" from_port = 8080 to_port = 8082 protocol = "tcp" self = true } egress { from_port = 0 to_port = 0 protocol = "-1" cidr_blocks = ["0.0.0.0/0"] } tags = local.tags }
resource "aws_iam_role" "execution" { name = "${local.name}-ecs-execution" assume_role_policy = data.aws_iam_policy_document.ecs_assume.json tags = local.tags }
data "aws_iam_policy_document" "ecs_assume" { statement { actions = ["sts:AssumeRole"] principals { type = "Service" identifiers = ["ecs-tasks.amazonaws.com"] } } }
resource "aws_iam_role_policy_attachment" "execution" { role = aws_iam_role.execution.name policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy" }
resource "aws_iam_role" "task" { for_each = local.services name = "${local.name}-${each.key}-task" assume_role_policy = data.aws_iam_policy_document.ecs_assume.json tags = local.tags }
data "aws_iam_policy_document" "core_policy" { statement { actions = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"] resources = ["${var.attachments_bucket_arn}/*"] } statement { actions = ["es:ESHttpGet", "es:ESHttpPost"] resources = ["${var.opensearch_domain_arn}/*"] } statement { actions = ["secretsmanager:GetSecretValue", "ssm:GetParameter", "ssm:GetParameters"] resources = var.core_secret_arns } }
data "aws_iam_policy_document" "relay_policy" { statement { actions = ["es:ESHttpGet", "es:ESHttpPost", "es:ESHttpPut", "es:ESHttpDelete"] resources = ["${var.opensearch_domain_arn}/*"] } statement { actions = ["secretsmanager:GetSecretValue", "ssm:GetParameter", "ssm:GetParameters"] resources = var.relay_secret_arns } }
data "aws_iam_policy_document" "nova_policy" { statement { actions = ["secretsmanager:GetSecretValue", "ssm:GetParameter", "ssm:GetParameters"] resources = var.nova_secret_arns } }
resource "aws_iam_role_policy" "task" { for_each = { core = data.aws_iam_policy_document.core_policy.json, relay = data.aws_iam_policy_document.relay_policy.json, nova = data.aws_iam_policy_document.nova_policy.json } name = "least-privilege" role = aws_iam_role.task[each.key].id policy = each.value }
resource "aws_cloudwatch_log_group" "service" { for_each = local.services name = "/taskmind/${var.environment}/${each.key}" retention_in_days = var.log_retention_days kms_key_id = var.cloudwatch_logs_kms_key_id tags = local.tags }
resource "aws_service_discovery_service" "service" { for_each = local.services name = each.key dns_config { namespace_id = aws_service_discovery_private_dns_namespace.this.id dns_records { ttl = 10 type = "A" } routing_policy = "MULTIVALUE" } health_check_custom_config { failure_threshold = 1 } tags = local.tags }
resource "aws_ecs_task_definition" "service" { for_each = local.services family = "${local.name}-${each.key}" network_mode = "awsvpc" requires_compatibilities = ["FARGATE"] cpu = each.value.cpu memory = each.value.memory execution_role_arn = aws_iam_role.execution.arn task_role_arn = aws_iam_role.task[each.key].arn container_definitions = jsonencode([{ name = each.key, image = var.service_images[each.key], essential = true, portMappings = [{ containerPort = each.value.port, protocol = "tcp" }], environment = concat([{ name = "SPRING_PROFILES_ACTIVE", value = "prod" }, { name = "TASKMIND_ENVIRONMENT", value = var.environment }], lookup(var.service_environment, each.key, [])), secrets = lookup(var.service_secrets, each.key, []), logConfiguration = { logDriver = "awslogs", options = { awslogs-group = aws_cloudwatch_log_group.service[each.key].name, awslogs-region = var.aws_region, awslogs-stream-prefix = "ecs" } } }]) tags = local.tags lifecycle { precondition { condition = alltrue([for secret in lookup(var.service_secrets, each.key, []) : anytrue([for arn in local.service_secret_arns[each.key] : secret.valueFrom == arn || startswith(secret.valueFrom, "${arn}:")])]) error_message = "Every service_secrets entry must use a valueFrom ARN listed in the matching <service>_secret_arns variable." } } }
resource "aws_ecs_service" "service" { for_each = local.services name = each.key cluster = aws_ecs_cluster.this.id task_definition = aws_ecs_task_definition.service[each.key].arn desired_count = each.value.desired launch_type = "FARGATE" enable_execute_command = var.enable_execute_command network_configuration { subnets = var.private_subnet_ids security_groups = [aws_security_group.ecs.id] assign_public_ip = false } service_registries { registry_arn = aws_service_discovery_service.service[each.key].arn } dynamic "load_balancer" { for_each = each.key == "core" ? [1] : [] content { target_group_arn = var.core_target_group_arn container_name = "core" container_port = 8080 } } tags = local.tags }
